services:
  # fyp_proxy:
  #   image: nginx
  #   networks:
  #     - outside
  #   ports:
  #     - 11811:11811
  #     - 11811:11811/udp
  #   volumes:
  #     - ./test_nginx.conf:/etc/nginx/nginx.conf
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
  fyp_ros_proxy:
    image: ken20020209/fyp_ros_proxy:latest
    ports:
      - 9089:9089
  fyp_ros_proxy_ip:
    image: ken20020209/fyp_ros_proxy:ip
    networks:
      -  outside
    deploy:
      mode: global
  # the fyp ros server can be scaled by the number of node
  fyp_ros_server: #optional 
    image: ken20020209/fyp_ros_server:latest
    networks:
      - outside 
    environment:
      - RECORD_STORAGE_PATH=/data/record
      - MAP_STORAGE_PATH=/data/map
      - DISCOVERY_SERVER=discoveryserver.ddns.net
      - CAMERA_URL=http://host.docker.internal:8000/effect
      - API_DATABASE_URL=http://host.docker.internal:5000
      - API_DATABASE_USERNAME=admin
      - API_DATABASE_PASSWORD=12345678
      - ROS_PROXY_URL=http://host.docker.internal:9089 # for get port and manger ip of task
      - ROS_PROXY_ENABLE=False
      - ROS_PROXY_IP_URL=http://host.docker.internal:9088/api/ros/ip #for get host ip
      # - discover_server=127.0.0.1 # for local test
    # volumes:
    #   - ./data/rosServer:/data
    extra_hosts:
    - "host.docker.internal:host-gateway"
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1

    # ports:
    #   - mode: host
    #     target: 11811
    #     published: 11811
    #     protocol: udp
      
      # - 9090-9120:9090-9120/udp #websocket
      # - 9090-9120:9090-9120 #websocket
      # - 6096-6126:6096-6126/udp #vnc
      # - 6096-6126:6096-6126 #vnc
      # - 11811:11811/udp #discovery server
      # - 11811:11811 #discovery server
      # - 11827-11847:11827-11847/udp #discovery server
      # - 11827-11847:11827-11847 #discovery server

    depends_on:
      - fyp_api_database

  fyp_web:
    image: ken20020209/fyp_web:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl/cert.pem:/etc/nginx/cert.pem
      - ./ssl/key.key:/etc/nginx/key.key
      - ./ssl/password.txt:/etc/nginx/password.txt
    depends_on:
      - fyp_api_database
  fyp_api_database:
    image: ken20020209/fyp_api_database:latest
    environment:
      - HOST_URL=https://www.ken20020209.com
      - DATA_STORAGE_PATH = data
      - SQLITE3_DATABASE_PATH = '../data/database/database.db'
      - NVIDIA_VISIBLE_DEVICES = all
    ports:
      - 5000:8000
    volumes:
      - ./data:/flask_service/data
      
  fyp_effect:
    tty: true
    image: ken20020209/fyp_ai_effect:latest
    ports:
      - 8000:8000
    deploy:
        replicas: 4
        resources:
            reservations:
                generic_resources:
                    - discrete_resource_spec:
                        kind: "NVIDIA-GPU"
                        value: 1

networks:
  outside:
      name: "host"
      external: true