services:
  fyp_ros_server: #optional
    image: ken20020209/fyp_ros_server:latest
    networks:
      - outside # bug in docker only work in host mode
    environment:
      - RECORD_STORAGE_PATH=/data/record
      - MAP_STORAGE_PATH=/data/map
      - DISCOVERY_SERVER=discoveryserver.ddns.net
      - CAMERA_URL=http://aieffect.ddns.net:8000/effect
      - API_DATABASE_URL=http://webserver.viewdns.net:5000
      - API_DATABASE_USERNAME=admin
      - API_DATABASE_PASSWORD=12345678
      # - discover_server=127.0.0.1 # for local test
    volumes:
      - ./data/rosServer:/data
    ports:
      - mode: host
      # - 9090-9120:9090-9120 #websocket
      # - 6096-6126:6096-6126 #vnc
      # - 11811:11811 #discovery server
      # - 11827-11847:11827-11847 #discovery server

    depends_on:
      - fyp_api_database

  fyp_web:
    image: ken20020209/fyp_web:latest
    ports:
      - 80:80
    depends_on:
      - fyp_api_database
  fyp_api_database:
    image: ken20020209/fyp_api_database:latest
    environment:
      - HOST_URL=http://webserver.viewdns.net:5000
      - DATA_STORAGE_PATH = data
      - SQLITE3_DATABASE_PATH = '../data/database/database.db'
      - NVIDIA_VISIBLE_DEVICES = all
    ports:
      - 5000:8000
    volumes:
      - ./data:/flask_service/data
      
  fyp_effect:
    tty: true
    image: ken20020209/fyp_ai_effect:latest
    ports:
      - 8000:8000
    deploy:
        replicas: 2
        resources:
            reservations:
                generic_resources:
                    - discrete_resource_spec:
                        kind: "NVIDIA-GPU"
                        value: 1

networks:
  outside:
      name: "host"
      external: true