services:
  fyp_ros_server: #optional
    image: ken20020209/fyp_ros_server:latest
    network_mode: host # bug in docker only work in host mode
    environment:
      - RECORD_STORAGE_PATH=/data/record
      - MAP_STORAGE_PATH=/data/map
      - DISCOVERY_SERVER=discoveryserver.ddns.net
      - CAMERA_URL=http://aieffect.ddns.net:8000/effect
      - API_DATABASE_URL=http://webserver.viewdns.net:5000
      - API_DATABASE_USERNAME=admin
      - API_DATABASE_PASSWORD=12345678
      # - discover_server=127.0.0.1 # for local test
    volumes:
      - ./data/rosServer:/data
    ports:
      - 9090-9120:9090-9120 #websocket
      - 6096-6126:6096-6126 #vnc
      - 11811:11811 #discovery server
      - 11827-11847:11827-11847 #discovery server
    depends_on:
      - fyp_api_database
